# Generated by Django 3.1 on 2020-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200818_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
